export const COMPANY_ASSET_DOMAINS = {
  "0700.HK": "tencent.com",
  "3690.HK": "meituan.com",
  "9988.HK": "alibabagroup.com",
  "9618.HK": "jd.com",
  "1024.HK": "kuaishou.com",
  "9888.HK": "baidu.com",
  "9999.HK": "neteasegames.com",
  "1810.HK": "mi.com",
  "2015.HK": "lixiang.com",
  "1211.HK": "bydglobal.com",
  "2330.TW": "tsmc.com",
  "6981.T": "murata.com",
  "8035.T": "tel.com",
  "6758.T": "sony.com",
  "7974.T": "nintendo.com",
  "9984.T": "group.softbank",
  "MUV2.DE": "munichre.com",
  "SAP.DE": "sap.com",
  "SIE.DE": "siemens.com",
  "RHM.DE": "rheinmetall.com",
  "ASML.AS": "asml.com",
  "UMG.AS": "universalmusic.com",
  "ITX.MC": "inditex.com",
  "IBE.MC": "iberdrola.com",
  "SAN.MC": "santander.com",
  "BBVA.MC": "bbva.com",
  "NVDA": "nvidia.com",
  "AVGO": "broadcom.com",
  "AMD": "amd.com",
  "MU": "micron.com",
  "MSFT": "microsoft.com",
  "META": "meta.com",
  "GOOGL": "google.com",
  "GOOG": "google.com",
  "AMZN": "amazon.com",
  "AAPL": "apple.com",
  "TSM": "tsmc.com",
  "ARM": "arm.com",
  "BILI": "bilibili.com",
  "PDD": "pinduoduo.com",
  "SE": "sea.com",
  "TTWO": "take2games.com",
  "EA": "ea.com",
};

const NAME_DOMAIN_RULES = [
  [/tencent/i, "tencent.com"],
  [/meituan/i, "meituan.com"],
  [/alibaba/i, "alibabagroup.com"],
  [/jd\.?com|jingdong/i, "jd.com"],
  [/kuaishou/i, "kuaishou.com"],
  [/baidu/i, "baidu.com"],
  [/netease/i, "neteasegames.com"],
  [/bilibili/i, "bilibili.com"],
  [/pdd|pinduoduo/i, "pinduoduo.com"],
  [/sea limited|\bsea\b/i, "sea.com"],
  [/taiwan semiconductor|tsmc/i, "tsmc.com"],
  [/murata/i, "murata.com"],
  [/micron/i, "micron.com"],
  [/universal music/i, "universalmusic.com"],
  [/munich re|muenchener/i, "munichre.com"],
  [/nvidia/i, "nvidia.com"],
  [/broadcom/i, "broadcom.com"],
  [/advanced micro devices|\bamd\b/i, "amd.com"],
  [/alphabet|google/i, "google.com"],
  [/meta platforms|facebook/i, "meta.com"],
  [/microsoft/i, "microsoft.com"],
  [/apple/i, "apple.com"],
  [/amazon/i, "amazon.com"],
  [/asml/i, "asml.com"],
  [/inditex|industria de diseno/i, "inditex.com"],
];

export function assetDomainForSymbol(symbol = "") {
  return COMPANY_ASSET_DOMAINS[String(symbol || "").toUpperCase()] || "";
}

export function assetDomainForName(name = "") {
  const text = String(name || "");
  return NAME_DOMAIN_RULES.find(([rule]) => rule.test(text))?.[1] || "";
}
